---
#
# Ansible managed
#
language: python

python:
  - "3.7"

services:
  - docker

env:
  global:
    namespace="robertdebock"
  matrix:
    - image="alpine" tag="latest"
    - image="alpine" tag="edge"
    - image="centos" tag="7"
    - image="centos" tag="latest"
    - image="debian" tag="latest"
    - image="debian" tag="bullseye"
    - image="fedora" tag="31"
    - image="fedora" tag="latest"
    - image="opensuse" tag="latest"
    - image="ubuntu" tag="bionic"

cache:
  - pip

install:
  - pip install --upgrade pip
  - pip install tox

script:
  - tox --parallel all

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  slack:
    secure: "LiwUFDHxV/zFmw9Hs5feg4zxV4o61ETM2AlaWf1R9Oa0mSBDWRLBRlQW1bRk2lOIS997aIn+vC+qaMTPgrHAz8ZxenhsFXQYdtjandp9G0mAAvOk3qOaKojPe/9MHYXiLJxU6gt4amy223t3j91+VgyvzXNKAmTOKxY5V/BJaeSQf7acVB3JLuH1kuB3KEya99UMm4D/f/lk83Hwwe3VPv02zzCTtyCqZ8oZxkBPZSivYsCyXHHup57W9t4XUo6slbeun4iwUbIxyJH2bvzMd/0Am3MwQ4yVDIrfVCk9L+v1M9z53wsHVFtsJRMR/ptRzRLesn8SG0573hYvo+nwK0wfiLn/0nx41onQb3eTGMo6c/eXTh2r5PiqOQOVUP9yOez/RWCTP/28zll2PaeBrCDGmOGanNyP8UCqvOqCTBRLy2gMlIaM2VvTD0jxR3w/vmpR4wMcKkYPipIFDu3nV9q/0kvWu47ZDLOGCBGc4A2qDOE1+jS641MEX5EVQ3giRdOh13jdtO79pZrnTJ8/Xu0iAYUMn5/les5AOn0DGEt+97gnFvJN+EXdyRnltehzf+WQ8slBiZRzw+Un5Z8DxYEezW1sJyRQ22pb5x1VkY4cz/ZbGRQ+PVGfJwczV5YJcSLYXWx3ACQoVlgCtUPTgAUO6EozjQK5a+5OPbi7Lm4="
  email: false
