---

- name: test if php_version_debian is set correctly
  ansible.builtin.assert:
    that:
      - php_version_debian is defined
      - php_version_debian is string

- name: test if php_version_suse is set correctly
  ansible.builtin.assert:
    that:
      - php_version_suse is defined
      - php_version_suse is number

- name: test if php_version_alpine is set correctly
  ansible.builtin.assert:
    that:
      - php_version_alpine is defined
      - php_version_alpine is number

- name: test if php_webserver is set correctly
  ansible.builtin.assert:
    that:
      - php_webserver is defined
      - php_webserer is string
      - php_webserver in ["httpd", "nginx"]

- name: test if php_fpm_listen is set correctly
  ansible.builtin.assert:
    that:
      - php_fpm_listen is defined
      - php_fpm_listen is string
    quiet: yes

- name: test if php_fpm_listen_owner is set correctly
  ansible.builtin.assert:
    that:
      - php_fpm_listen_owner is defined
      - php_fpm_listen_owner is string
    quiet: yes

- name: test if php_fpm_listen_group is set correctly
  ansible.builtin.assert:
    that:
      - php_fpm_listen_group is defined
      - php_fpm_listen_group is string
    quiet: yes

- name: test if php_fpm_listen_mode is set correctly
  ansible.builtin.assert:
    that:
      - php_fpm_listen_mode is defined
      - php_fpm_listen_mode is string
    quiet: yes

- name: test if php_fpm_pm is set correctly
  ansible.builtin.assert:
    that:
      - php_fpm_pm is defined
      - php_fpm_pm is string
      - php_fpm_pm in [ "dynamic", "ondemand", "static" ]
    quiet: yes

- name: test if php_fpm_pm_max_children is set correctly
  ansible.builtin.assert:
    that:
      - php_fpm_pm_max_children is defined
      - php_fpm_pm_max_children is number
      - php_fpm_pm_max_children > 0
    quiet: yes

- name: test if php_fpm_pm_start_servers is set correctly
  ansible.builtin.assert:
    that:
      - php_fpm_pm_start_servers is defined
      - php_fpm_pm_start_servers is number
      - php_fpm_pm_start_servers > 0
    quiet: yes

- name: test if php_fpm_pm_min_spare_servers is set correctly
  ansible.builtin.assert:
    that:
      - php_fpm_pm_min_spare_servers is defined
      - php_fpm_pm_min_spare_servers is number
      - php_fpm_pm_min_spare_servers > 0
    quiet: yes

- name: test if php_fpm_pm_max_spare_servers is set correctly
  ansible.builtin.assert:
    that:
      - php_fpm_pm_max_spare_servers is defined
      - php_fpm_pm_max_spare_servers is number
      - php_fpm_pm_max_spare_servers > 0
    quiet: yes
