---
# tasks file for php_fpm
- name: include assert.yml
  include_tasks: assert.yml

- name: install php-fpm
  package:
    name: "{{ php_fpm_packages }}"
    state: present

- name: place php-fpm configuration
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  notify:
    - restart php-fpm
  loop:
    - src: php-fpm.conf.j2
      dest: "{{ php_fpm_directory }}/php-fpm.conf"
    - src: www.conf.j2
      dest: "{{ php_fpm_include_directory }}/www.conf"
  loop_control:
    label: "{{ item.src }}"

- name: start php-fpm
  block:
    - name: normal start
      service:
        name: "{{ php_fpm_service }}"
        state: started
        enabled: yes
  rescue:
    - name: collect information
      command: "{{ item }}"
      loop:
        - systemctl status "{{ php_fpm_service }}"
        - journalctl -xe
      register: php_fpm_collect_information
    - name: show information
      debug:
        msg: "{{ item }}"
      loop: "{{ php_fpm_collect_information.results }}"
