---
# tasks file for php_fpm
- name: include assert.yml
  include_tasks: assert.yml

- name: install php-fpm
  package:
    name: "{{ php_fpm_packages }}"
    state: present
  register: php_fpm_install_php_fpm
  until: php_fpm_install_php_fpm is succeeded
  retries: 3

- name: place php-fpm configuration
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  notify:
    - restart php-fpm
  loop:
    - src: php-fpm.conf.j2
      dest: "{{ php_fpm_directory }}/php-fpm.conf"
    - src: www.conf.j2
      dest: "{{ php_fpm_include_directory }}/www.conf"
  loop_control:
    label: "{{ item.src }}"

- name: start php-fpm
  service:
    name: "{{ php_fpm_service }}"
    state: started
    enabled: yes
